#!/bin/sh
# this file is used to read a list of account names and passwords and create system accounts
# NOTE:  make sure to change the date in the useradd command
# NOTE:  works in conjunction with accounts.txt file, which contains username (u) and plaintext password (p), separated by a space

cat accounts.txt | while read u p
do
pass=$(perl -e 'print crypt($ARGV[0], "lkjasdflj")' $p)
echo "$u - $p - $pass"
useradd -e 2016-02-07 -m -p $pass $u
done
